name: finance-tracker
region: nyc

databases:
  - name: finance-db
    engine: PG
    version: "15"
    production: true
    cluster_name: finance-db-cluster

services:
  # Backend API Service
  - name: api
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${finance-db.DATABASE_URL}
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "CHANGE_THIS_TO_A_SECURE_RANDOM_STRING"
      - key: ALGORITHM
        scope: RUN_TIME
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_TIME
        value: "30"
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: "https://YOUR_FRONTEND_URL.ondigitalocean.app"
    
    health_check:
      http_path: /api/v1/health
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    run_command: |
      cd /app && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000

  # Frontend Static Site
  - name: frontend
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    
    envs:
      - key: VITE_API_BASE_URL
        scope: BUILD_TIME
        value: "https://api-YOUR_APP_NAME.ondigitalocean.app"
    
    routes:
      - path: /
    
    static_sites:
      - name: frontend
        build_command: npm install && npm run build
        output_dir: dist
        catchall_document: index.html
        environment_slug: node-js
