"""Add image_url to wishlist_items

Revision ID: 7224d0b97b6c
Revises: ccc73cb2c9e9
Create Date: 2025-12-31 11:19:52.002903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7224d0b97b6c'
down_revision: Union[str, Sequence[str], None] = 'ccc73cb2c9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_items', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist_items', 'image_url')
    # ### end Alembic commands ###
